
import { Customer, Partner, Product } from '../types';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'JumpCloud',
    website: 'jumpcloud.com',
    category: 'Identity Management',
    description: 'Cloud-based directory service and identity management platform',
    status: 'active',
    customersCount: 8,
    plans: [
      {
        id: '1-1',
        name: 'Core',
        price: 2.50,
        billing: 'monthly',
        features: ['User Management', 'SSO', 'Basic MFA'],
        userLimit: 10,
      },
      {
        id: '1-2',
        name: 'Business',
        price: 8.00,
        billing: 'monthly',
        features: ['Advanced SSO', 'RADIUS', 'LDAP'],
        userLimit: 50,
        isPopular: true,
      },
      {
        id: '1-3',
        name: 'Enterprise',
        price: 20.00,
        billing: 'monthly',
        features: ['Everything in Business', 'Advanced MFA', 'API Access'],
        userLimit: 1000,
      }
    ],
    price: 299.99,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '2',
    name: 'Scalefusion',
    website: 'scalefusion.com',
    category: 'Mobile Device Management',
    description: 'Unified endpoint management and mobile device management solution',
    status: 'active',
    customersCount: 5,
    plans: [
      {
        id: '2-1',
        name: 'Growth',
        price: 2.00,
        billing: 'monthly',
        features: ['Device Management', 'App Management', 'Basic Security'],
        userLimit: 25,
      },
      {
        id: '2-2',
        name: 'Business',
        price: 4.00,
        billing: 'monthly',
        features: ['Advanced Security', 'Kiosk Mode', 'Geofencing'],
        userLimit: 100,
        isPopular: true,
      },
      {
        id: '2-3',
        name: 'Enterprise',
        price: 7.00,
        billing: 'monthly',
        features: ['Custom Branding', 'Advanced Analytics', 'Priority Support'],
      }
    ],
    price: 199.99,
    createdAt: new Date('2024-01-15'),
  },
  {
    id: '3',
    name: 'Google Workspace',
    website: 'workspace.google.com',
    category: 'Productivity Suite',
    description: 'Cloud-based productivity and collaboration tools',
    status: 'active',
    customersCount: 12,
    plans: [
      {
        id: '3-1',
        name: 'Business Starter',
        price: 6.00,
        billing: 'monthly',
        features: ['Gmail', 'Drive (30GB)', 'Meet', 'Calendar'],
        userLimit: 300,
      },
      {
        id: '3-2',
        name: 'Business Standard',
        price: 12.00,
        billing: 'monthly',
        features: ['Drive (2TB)', 'Enhanced Meet', 'Shared Drives'],
        userLimit: 300,
        isPopular: true,
      },
      {
        id: '3-3',
        name: 'Business Plus',
        price: 18.00,
        billing: 'monthly',
        features: ['Drive (5TB)', 'Advanced Security', 'eDiscovery'],
        userLimit: 300,
      }
    ],
    price: 149.99,
    createdAt: new Date('2024-02-01'),
  },
  {
    id: '4',
    name: 'Microsoft 365',
    website: 'microsoft.com/microsoft-365',
    category: 'Productivity Suite',
    description: 'Integrated cloud-based productivity and business applications',
    status: 'active',
    customersCount: 15,
    plans: [
      {
        id: '4-1',
        name: 'Business Basic',
        price: 6.00,
        billing: 'monthly',
        features: ['Exchange', 'OneDrive (1TB)', 'Teams', 'SharePoint'],
        userLimit: 300,
      },
      {
        id: '4-2',
        name: 'Business Standard',
        price: 12.50,
        billing: 'monthly',
        features: ['Office Apps', 'Desktop Versions', 'Advanced Teams'],
        userLimit: 300,
        isPopular: true,
      },
      {
        id: '4-3',
        name: 'Business Premium',
        price: 22.00,
        billing: 'monthly',
        features: ['Advanced Security', 'Device Management', 'Advanced Compliance'],
        userLimit: 300,
      }
    ],
    price: 179.99,
    createdAt: new Date('2024-02-15'),
  },
  {
    id: '5',
    name: 'Okta',
    website: 'okta.com',
    category: 'Identity Management',
    description: 'Enterprise identity and access management platform',
    status: 'active',
    customersCount: 6,
    plans: [
      {
        id: '5-1',
        name: 'Workforce Identity',
        price: 2.00,
        billing: 'monthly',
        features: ['SSO', 'MFA', 'Lifecycle Management'],
      },
      {
        id: '5-2',
        name: 'Customer Identity',
        price: 0.55,
        billing: 'monthly',
        features: ['Customer Registration', 'Social Login', 'Progressive Profiling'],
        isPopular: true,
      }
    ],
    price: 399.99,
    createdAt: new Date('2024-03-01'),
  },
  {
    id: '6',
    name: 'Slack',
    website: 'slack.com',
    category: 'Communication',
    description: 'Business communication and collaboration platform',
    status: 'active',
    customersCount: 10,
    plans: [
      {
        id: '6-1',
        name: 'Pro',
        price: 7.25,
        billing: 'monthly',
        features: ['Unlimited Messages', 'Apps & Integrations', 'Guest Access'],
      },
      {
        id: '6-2',
        name: 'Business+',
        price: 12.50,
        billing: 'monthly',
        features: ['SAML SSO', 'Compliance Exports', '99.99% Uptime SLA'],
        isPopular: true,
      },
      {
        id: '6-3',
        name: 'Enterprise Grid',
        price: 19.00,
        billing: 'monthly',
        features: ['Advanced Security', 'Data Loss Prevention', 'Enterprise Key Management'],
      }
    ],
    price: 89.99,
    createdAt: new Date('2024-03-15'),
  },
];

export const mockPartners: Partner[] = [
  {
    id: '1',
    name: 'John Smith',
    email: 'john@techsolutions.com',
    company: 'Tech Solutions Inc',
    specialization: 'Enterprise Software',
    identity: 'system-integrator',
    customersCount: 15,
    totalValue: 250000,
    status: 'active',
    createdAt: new Date('2024-01-15'),
    agreementSigned: true,
    agreementDate: new Date('2024-01-10'),
    productTypes: ['Identity Management', 'Productivity Suite'],
    paymentTerms: 'net-30',
    assignedEmployeeId: '1',
    zone: 'north',
  },
  {
    id: '2',
    name: 'Sarah Johnson',
    email: 'sarah@digitalcorp.com',
    company: 'Digital Corp',
    specialization: 'Digital Marketing',
    identity: 'digital-marketer',
    customersCount: 12,
    totalValue: 180000,
    status: 'active',
    createdAt: new Date('2024-02-01'),
    agreementSigned: true,
    agreementDate: new Date('2024-01-28'),
    productTypes: ['Communication', 'Mobile Device Management'],
    paymentTerms: 'net-60',
    assignedEmployeeId: '2',
    zone: 'east',
  },
  {
    id: '3',
    name: 'Mike Chen',
    email: 'mike@innovate.com',
    company: 'Innovate LLC',
    specialization: 'Cloud Services',
    identity: 'web-app-developer',
    customersCount: 8,
    totalValue: 120000,
    status: 'active',
    createdAt: new Date('2024-03-10'),
    agreementSigned: false,
    productTypes: ['Productivity Suite', 'Identity Management'],
    paymentTerms: 'monthly',
    assignedEmployeeId: '3',
    zone: 'west',
  },
];

export const mockCustomers: Customer[] = [
  {
    id: '1',
    name: 'Alice Wilson',
    email: 'alice@example.com',
    phone: '+1 (555) 123-4567',
    company: 'Acme Corp',
    status: 'active',
    partnerId: '1',
    productIds: ['1', '3', '4'],
    createdAt: new Date('2024-04-01'),
    value: 25000,
    zone: 'north',
  },
  {
    id: '2',
    name: 'Bob Martinez',
    email: 'bob@startup.io',
    phone: '+1 (555) 234-5678',
    company: 'Startup Inc',
    status: 'pending',
    partnerId: '2',
    productIds: ['2', '6'],
    createdAt: new Date('2024-05-15'),
    value: 15000,
    zone: 'south',
  },
  {
    id: '3',
    name: 'Carol Davis',
    email: 'carol@enterprise.com',
    phone: '+1 (555) 345-6789',
    company: 'Enterprise Ltd',
    status: 'active',
    partnerId: '1',
    productIds: ['1', '4', '5'],
    createdAt: new Date('2024-05-20'),
    value: 45000,
    zone: 'east',
  },
  {
    id: '4',
    name: 'David Brown',
    email: 'david@tech.com',
    phone: '+1 (555) 456-7890',
    company: 'Tech Innovations',
    status: 'inactive',
    partnerId: '3',
    productIds: ['3', '6'],
    createdAt: new Date('2024-06-01'),
    value: 8000,
    zone: 'west',
  },
];
