import { Customer, Partner, Product } from '../types';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'JumpCloud',
    website: 'jumpcloud.com',
    category: 'Identity Management',
    description: 'Cloud-based directory service and identity management platform',
    status: 'active',
    customersCount: 8,
    price: 299.99,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '2',
    name: 'Scalefusion',
    website: 'scalefusion.com',
    category: 'Mobile Device Management',
    description: 'Unified endpoint management and mobile device management solution',
    status: 'active',
    customersCount: 5,
    price: 199.99,
    createdAt: new Date('2024-01-15'),
  },
  {
    id: '3',
    name: 'Google Workspace',
    website: 'workspace.google.com',
    category: 'Productivity Suite',
    description: 'Cloud-based productivity and collaboration tools',
    status: 'active',
    customersCount: 12,
    price: 149.99,
    createdAt: new Date('2024-02-01'),
  },
  {
    id: '4',
    name: 'Microsoft 365',
    website: 'microsoft.com/microsoft-365',
    category: 'Productivity Suite',
    description: 'Integrated cloud-based productivity and business applications',
    status: 'active',
    customersCount: 15,
    price: 179.99,
    createdAt: new Date('2024-02-15'),
  },
  {
    id: '5',
    name: 'Okta',
    website: 'okta.com',
    category: 'Identity Management',
    description: 'Enterprise identity and access management platform',
    status: 'active',
    customersCount: 6,
    price: 399.99,
    createdAt: new Date('2024-03-01'),
  },
  {
    id: '6',
    name: 'Slack',
    website: 'slack.com',
    category: 'Communication',
    description: 'Business communication and collaboration platform',
    status: 'active',
    customersCount: 10,
    price: 89.99,
    createdAt: new Date('2024-03-15'),
  },
];

export const mockPartners: Partner[] = [
  {
    id: '1',
    name: 'John Smith',
    email: 'john@techsolutions.com',
    company: 'Tech Solutions Inc',
    specialization: 'Enterprise Software',
    customersCount: 15,
    totalValue: 250000,
    status: 'active',
    createdAt: new Date('2024-01-15'),
    agreementSigned: true,
    agreementDate: new Date('2024-01-10'),
    productTypes: ['Identity Management', 'Productivity Suite'],
    paymentTerms: 'net-30',
    assignedEmployeeId: '1',
  },
  {
    id: '2',
    name: 'Sarah Johnson',
    email: 'sarah@digitalcorp.com',
    company: 'Digital Corp',
    specialization: 'Digital Marketing',
    customersCount: 12,
    totalValue: 180000,
    status: 'active',
    createdAt: new Date('2024-02-01'),
    agreementSigned: true,
    agreementDate: new Date('2024-01-28'),
    productTypes: ['Communication', 'Mobile Device Management'],
    paymentTerms: 'net-60',
    assignedEmployeeId: '2',
  },
  {
    id: '3',
    name: 'Mike Chen',
    email: 'mike@innovate.com',
    company: 'Innovate LLC',
    specialization: 'Cloud Services',
    customersCount: 8,
    totalValue: 120000,
    status: 'active',
    createdAt: new Date('2024-03-10'),
    agreementSigned: false,
    productTypes: ['Productivity Suite', 'Identity Management'],
    paymentTerms: 'monthly',
    assignedEmployeeId: '3',
  },
];

export const mockCustomers: Customer[] = [
  {
    id: '1',
    name: 'Alice Wilson',
    email: 'alice@example.com',
    phone: '+1 (555) 123-4567',
    company: 'Acme Corp',
    status: 'active',
    partnerId: '1',
    productIds: ['1', '3', '4'],
    createdAt: new Date('2024-04-01'),
    value: 25000,
  },
  {
    id: '2',
    name: 'Bob Martinez',
    email: 'bob@startup.io',
    phone: '+1 (555) 234-5678',
    company: 'Startup Inc',
    status: 'pending',
    partnerId: '2',
    productIds: ['2', '6'],
    createdAt: new Date('2024-05-15'),
    value: 15000,
  },
  {
    id: '3',
    name: 'Carol Davis',
    email: 'carol@enterprise.com',
    phone: '+1 (555) 345-6789',
    company: 'Enterprise Ltd',
    status: 'active',
    partnerId: '1',
    productIds: ['1', '4', '5'],
    createdAt: new Date('2024-05-20'),
    value: 45000,
  },
  {
    id: '4',
    name: 'David Brown',
    email: 'david@tech.com',
    phone: '+1 (555) 456-7890',
    company: 'Tech Innovations',
    status: 'inactive',
    partnerId: '3',
    productIds: ['3', '6'],
    createdAt: new Date('2024-06-01'),
    value: 8000,
  },
];
