import { Task } from '@/types';

export const mockTasks: Task[] = [
  {
    id: '1',
    title: 'Follow up with Acme Corp on Microsoft 365 renewal',
    description: 'Customer expressed concerns about pricing. Need to discuss volume discounts and additional features.',
    type: 'renewal-follow-up',
    priority: 'high',
    status: 'pending',
    assignedTo: '2',
    customerId: '1',
    partnerId: '1',
    dueDate: new Date('2024-07-20'),
    createdAt: new Date('2024-07-10'),
    tags: ['renewal', 'pricing', 'microsoft'],
    estimatedHours: 2,
  },
  {
    id: '2',
    title: 'Complete partner onboarding for Digital Corp',
    description: 'Finalize training sessions and setup partner portal access.',
    type: 'partner-onboarding',
    priority: 'medium',
    status: 'in-progress',
    assignedTo: '3',
    partnerId: '2',
    dueDate: new Date('2024-07-25'),
    createdAt: new Date('2024-07-05'),
    tags: ['onboarding', 'training'],
    estimatedHours: 8,
    actualHours: 4,
  },
  {
    id: '3',
    title: 'Technical support for JumpCloud integration',
    description: 'Help Enterprise Ltd resolve SSO configuration issues.',
    type: 'technical-support',
    priority: 'urgent',
    status: 'in-progress',
    assignedTo: '4',
    customerId: '3',
    dueDate: new Date('2024-07-16'),
    createdAt: new Date('2024-07-14'),
    tags: ['technical', 'sso', 'jumpcloud'],
    estimatedHours: 4,
    actualHours: 2,
  },
  {
    id: '4',
    title: 'Customer training for Google Workspace',
    description: 'Conduct training session for new Google Workspace features.',
    type: 'training',
    priority: 'medium',
    status: 'completed',
    assignedTo: '5',
    customerId: '2',
    dueDate: new Date('2024-07-12'),
    createdAt: new Date('2024-07-01'),
    completedAt: new Date('2024-07-11'),
    tags: ['training', 'google-workspace'],
    estimatedHours: 3,
    actualHours: 3,
  },
  {
    id: '5',
    title: 'Outreach to prospect for Slack Enterprise',
    description: 'Initial contact with potential customer for Slack Enterprise Grid solution.',
    type: 'customer-outreach',
    priority: 'low',
    status: 'pending',
    assignedTo: '6',
    dueDate: new Date('2024-07-30'),
    createdAt: new Date('2024-07-08'),
    tags: ['outreach', 'prospect', 'slack'],
    estimatedHours: 1,
  },
  {
    id: '6',
    title: 'Urgent: Scalefusion renewal overdue',
    description: 'Startup Inc renewal is 5 days overdue. Need immediate follow-up.',
    type: 'renewal-follow-up',
    priority: 'urgent',
    status: 'pending',
    assignedTo: '3',
    customerId: '2',
    partnerId: '2',
    dueDate: new Date('2024-07-10'),
    createdAt: new Date('2024-07-09'),
    tags: ['renewal', 'overdue', 'scalefusion'],
    estimatedHours: 2,
  },
];