
import { User } from '../types';

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'John Admin',
    email: 'john.admin@company.com',
    phone: '+1 (555) 100-0001',
    role: 'admin',
    department: 'Administration',
    status: 'active',
    createdAt: new Date('2024-01-01'),
    lastLogin: new Date('2024-06-08'),
  },
  {
    id: '2',
    name: 'Sarah Manager',
    email: 'sarah.manager@company.com',
    phone: '+1 (555) 100-0002',
    role: 'manager',
    reportingTo: '1',
    department: 'Sales',
    status: 'active',
    createdAt: new Date('2024-01-15'),
    lastLogin: new Date('2024-06-07'),
  },
  {
    id: '3',
    name: 'Mike Team Leader',
    email: 'mike.lead@company.com',
    phone: '+1 (555) 100-0003',
    role: 'team-leader',
    reportingTo: '2',
    department: 'Sales',
    status: 'active',
    createdAt: new Date('2024-02-01'),
    lastLogin: new Date('2024-06-08'),
  },
  {
    id: '4',
    name: 'Anna Assistant Manager',
    email: 'anna.assistant@company.com',
    phone: '+1 (555) 100-0004',
    role: 'assistant-manager',
    reportingTo: '2',
    department: 'Sales',
    status: 'active',
    createdAt: new Date('2024-02-15'),
    lastLogin: new Date('2024-06-06'),
  },
  {
    id: '5',
    name: 'David FSR',
    email: 'david.fsr@company.com',
    phone: '+1 (555) 100-0005',
    role: 'fsr',
    reportingTo: '3',
    department: 'Field Sales',
    status: 'active',
    createdAt: new Date('2024-03-01'),
    lastLogin: new Date('2024-06-08'),
  },
  {
    id: '6',
    name: 'Lisa BDE',
    email: 'lisa.bde@company.com',
    phone: '+1 (555) 100-0006',
    role: 'bde',
    reportingTo: '3',
    department: 'Business Development',
    status: 'active',
    createdAt: new Date('2024-03-15'),
    lastLogin: new Date('2024-06-07'),
  },
  {
    id: '7',
    name: 'Tom BDE',
    email: 'tom.bde@company.com',
    phone: '+1 (555) 100-0007',
    role: 'bde',
    reportingTo: '4',
    department: 'Business Development',
    status: 'active',
    createdAt: new Date('2024-04-01'),
    lastLogin: new Date('2024-06-08'),
  },
];
