
import { Customer, Partner } from '../types';

export const mockPartners: Partner[] = [
  {
    id: '1',
    name: 'John Smith',
    email: 'john@techsolutions.com',
    company: 'Tech Solutions Inc',
    specialization: 'Enterprise Software',
    customersCount: 15,
    totalValue: 250000,
    status: 'active',
    createdAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    name: 'Sarah Johnson',
    email: 'sarah@digitalcorp.com',
    company: 'Digital Corp',
    specialization: 'Digital Marketing',
    customersCount: 12,
    totalValue: 180000,
    status: 'active',
    createdAt: new Date('2024-02-01'),
  },
  {
    id: '3',
    name: 'Mike Chen',
    email: 'mike@innovate.com',
    company: 'Innovate LLC',
    specialization: 'Cloud Services',
    customersCount: 8,
    totalValue: 120000,
    status: 'active',
    createdAt: new Date('2024-03-10'),
  },
];

export const mockCustomers: Customer[] = [
  {
    id: '1',
    name: 'Alice Wilson',
    email: 'alice@example.com',
    phone: '+1 (555) 123-4567',
    company: 'Acme Corp',
    status: 'active',
    partnerId: '1',
    createdAt: new Date('2024-04-01'),
    value: 25000,
  },
  {
    id: '2',
    name: 'Bob Martinez',
    email: 'bob@startup.io',
    phone: '+1 (555) 234-5678',
    company: 'Startup Inc',
    status: 'pending',
    partnerId: '2',
    createdAt: new Date('2024-05-15'),
    value: 15000,
  },
  {
    id: '3',
    name: 'Carol Davis',
    email: 'carol@enterprise.com',
    phone: '+1 (555) 345-6789',
    company: 'Enterprise Ltd',
    status: 'active',
    partnerId: '1',
    createdAt: new Date('2024-05-20'),
    value: 45000,
  },
  {
    id: '4',
    name: 'David Brown',
    email: 'david@tech.com',
    phone: '+1 (555) 456-7890',
    company: 'Tech Innovations',
    status: 'inactive',
    partnerId: '3',
    createdAt: new Date('2024-06-01'),
    value: 8000,
  },
];
